import { Metadata } from "next"

export const metadata : Metadata = {
  title: {
    absolute : "Absolute title",
    default : "Default title all over pages",
    // template : "%s | use child param as title template"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{
          backgroundColor:'lightblue',
          padding : '1em',
          flex : '1'
        }}>
          <h1>Header</h1>
        </header>
        <div style={{
          backgroundColor : 'lightgreen',
          padding: '1em',
          flex : '5'
        }}>
          {children}
        </div>
        <footer style = {{
          backgroundColor : 'lightgrey',
          padding:'1em',
          flex: '2'
        }}>
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  )
}
